language: R
cache: packages
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel
      env: R_CODECOV=true

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libcurl4-openssl-dev libv8-3.14-dev netcdf-bin
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::install_github("mikejohnson51/HydroData", ref = "restructure")'
  
env:
   global:
     - R_BUILD_ARGS="--no-vignettes --no-manual"
     - R_CHECK_ARGS="--no-vignettes --no-manual --as-cran"
     - NOT_CRAN="true"
     - _R_CHECK_FORCE_SUGGESTS_=false

warnings_are_errors: false

r_github_packages:
  - jimhester/covr
  - mikejohnson51/AOI
  

after_success:
  - if [[ "${R_CODECOV}" ]]; then travis_wait 20 R -e 'covr::coveralls()'; fi

notifications:
  email:
    on_success: change
    on_failure: change